#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/Nazotoki
#    username: postgres
#    password: postgres

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://dpg-cvno13p5pdvs73bavbag-a.oregon-postgres.render.com:5432/nazotoki
#    username: nazotoki_user
#    password: y3ZGRteHnbeI1TFCALrqB1hHTdTsIMAw

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Nazotoki
    username: postgres
    password: postgres
